# Generated by Django 4.2.4 on 2023-08-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('doctor', models.CharField(max_length=100)),
                ('type_of_glass', models.CharField(blank=True, max_length=100)),
                ('type_of_lenses', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_up', models.DecimalField(decimal_places=2, max_digits=10)),
                ('residual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('right_sph', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('right_cyl', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('right_axis', models.IntegerField(blank=True, null=True)),
                ('left_sph', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('left_cyl', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('left_axis', models.IntegerField(blank=True, null=True)),
                ('addition', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
