# Generated by Django 4.2.4 on 2023-08-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddClient',
            new_name='Clients',
        ),
    ]
