# Generated by Django 4.2 on 2024-01-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_clients_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='paid_up',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='price',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='residual',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='type_of_glass',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='type_of_lenses',
        ),
    ]
